### ISSUE TITLE
web.config

### ISSUE THREAD

**Issue by aarongustafson** [brzez/js-dungeon-wanderer#1]
We need Node projects to include a config file telling IIS what to do. Here’s a template: https://a-k-apart.com/webconfigs/web.config.node.txt

**Comment by brzez** [comment]
Hey

I've added web.config
The node entry point is _server.js_, so I've changed that in the template.

I have disabled the

``` xml
<action type="Rewrite" url="public{REQUEST_URI}"/>
```

rule.
This isn't optimal, but node handles gzipping and cache-control, so I would need to configure that in iis. 
(Or else I would fail the 10kb limit)

I've also added how to build the app to the readme. 
It's just a standard

``` js
npm install && npm run build
```

**Comment by aarongustafson** [comment]
Not sure what’s going on, but I am getting a blank screen & a 404 error: http://dungeon-wanderer-10kapart2016.azurewebsites.net/

**Comment by brzez** [comment]
Did everything build properly, do you have any logs or any more info?

I've set up an azure trial and will try to make it work somehow.

**Comment by aarongustafson** [comment]
I’m sorry, I have about 30 entries still to get through. If you can look
into it, I’ll circle back once I get through this stuff.

**Comment by brzez** [comment]
Sure, no problem.

I've reproduced the bug, reading the azure docs now.
As I understand azure doesn't build my project, it just does `npm install --production` and then tries to run _server.js_, which doesn't exist.
The perfect solution would be to make azure build the project somehow, but committing the built project should also work.

**Comment by brzez** [comment]
OK.
I think I got it.

I've created a deploy script in which I do `npm install` (w/o the **--production** flag)
Then I run `npm run build` and it works.

http://dungeon-wanderer.azurewebsites.net/

So, the release process for me was (using azure-cli)

```
azure site create --git dungeon-wanderer
git push azure master
```

**Comment by aarongustafson** [comment]
Hmm, I’m not sure what that means on our end. Let me check in with @molant.

**Comment by molant** [comment]
@brzez the problem is that the built output doesn't get to our azure website.
There are 2 options:
1. Add the output of `npm run build` to this repo (this will be the easiest)
1. Add a custom script for the deployment. There are some examples like [this for bower and grunt](https://gist.github.com/jasonruesch/9373695) but I haven't tested them (although I've used them before). For this case I would recommend configuring your azurewebsite to be deployed automatically on git push so you can see if there is any issue.

I've tried running `npm run build` from the site after installing gulp but I'm getting some errors:

```
\\100.68.10.85\volume-17-default\4f2ffdb6728fe33a2e64\512ba8bb9b1342be945ab654f9358f6a\site\wwwroot\node_modules\when\lib\decorators\unhandledRejection.js:80
        throw e;
        ^
Error: D:\home\site\wwwroot\stylus\index.styl:74:14





--------------------^
   75| 

failed to locate @import file \\100.68.10.85\volume-17-default\4f2ffdb6728fe33a2e64\512ba8bb9b1342be945ab654f9358f6a\site\wwwroot\node_modules\stylus\lib\functions.styl

    at Evaluator.visitImport (\\100.68.10.85\volume-17-default\4f2ffdb6728fe33a2e64\512ba8bb9b1342be945ab654f9358f6a\site\wwwroot\node_modules\stylus\lib\visitor\evaluator.js:915:21)
    at Evaluator.Visitor.visit (\\100.68.10.85\volume-17-default\4f2ffdb6728fe33a2e64\512ba8bb9b1342be945ab654f9358f6a\site\wwwroot\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (\\100.68.10.85\volume-17-default\4f2ffdb6728fe33a2e64\512ba8bb9b1342be945ab654f9358f6a\site\wwwroot\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitRoot (\\100.68.10.85\volume-17-default\4f2ffdb6728fe33a2e64\512ba8bb9b1342be945ab654f9358f6a\site\wwwroot\node_modules\stylus\lib\visitor\evaluator.js:707:27)
    at Evaluator.Visitor.visit (\\100.68.10.85\volume-17-default\4f2ffdb6728fe33a2e64\512ba8bb9b1342be945ab654f9358f6a\site\wwwroot\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (\\100.68.10.85\volume-17-default\4f2ffdb6728fe33a2e64\512ba8bb9b1342be945ab654f9358f6a\site\wwwroot\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.evaluate (\\100.68.10.85\volume-17-default\4f2ffdb6728fe33a2e64\512ba8bb9b1342be945ab654f9358f6a\site\wwwroot\node_modules\stylus\lib\visitor\evaluator.js:247:15)
    at Renderer.render (\\100.68.10.85\volume-17-default\4f2ffdb6728fe33a2e64\512ba8bb9b1342be945ab654f9358f6a\site\wwwroot\node_modules\stylus\lib\renderer.js:86:26)
    at dispatch (\\100.68.10.85\volume-17-default\4f2ffdb6728fe33a2e64\512ba8bb9b1342be945ab654f9358f6a\site\wwwroot\node_modules\when\node.js:71:15)
    at callAndResolve (\\100.68.10.85\volume-17-default\4f2ffdb6728fe33a2e64\512ba8bb9b1342be945ab654f9358f6a\site\wwwroot\node_modules\when\lib\apply.js:30:12)


npm ERR! Windows_NT 6.2.9200
npm ERR! argv "D:\\Program Files (x86)\\nodejs\\6.3.0\\node.exe" "D:\\Program Files (x86)\\npm\\3.10.3\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! a-k-apart@ build: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the a-k-apart@ build script 'gulp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the a-k-apart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs a-k-apart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls a-k-apart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\home\site\wwwroot\npm-debug.log
```

**Comment by brzez** [comment]
@molant did you check the 72a3477c2637ae2e0ca77aada76521f06ae1817c ?

I've created a deploy script, and it works (at least for me)

```
azure site create --git dungeon-wanderer
git push azure master
```

The git push will do a `npm install` and then a `npm run build` and it worked for me.
I have no idea how to use azure, so if it doesn't work for you, then sure, I'll just commit the built files.

**Comment by molant** [comment]
working!
http://dungeon-wanderer-10kapart2016.azurewebsites.net/

Thanks!

**Comment by brzez** [comment]
Awesome :+1:

**Comment by aarongustafson** [comment]
Yay! Thanks @molant!


## 

Cheers,

Aaron
